using System;

namespace Molca.Editor.Licensing
{
    /// <summary>
    /// Distribution-fixed configuration for the developer license gate: where the activation
    /// server lives, the public Google OAuth client id, and the public key entitlements are
    /// verified against. None of these are secrets — the signing <b>private</b> key lives only on
    /// the server (Secret Manager), and the allow-list lives only on the server.
    /// </summary>
    /// <remarks>
    /// Fill these in for your distribution. Until every placeholder is replaced,
    /// <see cref="IsConfigured"/> is <c>false</c> and <see cref="LicenseBuildGate"/> stays inert —
    /// so merging the licensing feature never blocks builds in a fork that has not set it up yet.
    /// The public-key coordinates are generated by the separately deployed Molca control plane.
    /// </remarks>
    internal static class DevLicenseConfig
    {
        /// <summary>Deployed Cloud Run base URL, e.g. <c>https://molca-license-abc123.run.app</c>.</summary>
        public const string ServerBaseUrl = "https://unity.molca.id";

        /// <summary>Google OAuth "Desktop app" client id (loopback + PKCE).</summary>
        public const string GoogleClientId = "1062042004243-9rakscb1k6845t7n68tu27u7brs620ee.apps.googleusercontent.com";

        /// <summary>OAuth scopes requested; <c>email</c> is what the allow-list matches on.</summary>
        public const string GoogleScope = "openid email profile";

        /// <summary>RSA public key modulus (standard base64) from key-gen. RSA — not ECDSA —
        /// because Unity's Mono editor runtime does not implement <c>ECDsa</c>.</summary>
        public const string PublicKeyModulusBase64 = "sXNi2SdsfqbAfbCJ0HxBzx+UgkXrQXx6FSCKFglq+6ppqhMj+2a/FcXX1ErCGZX5KX2xJQtGjvEQxBBvAS7sYbJyuOx6jfM8p3SCJhnEEjaQ4dWcuBWIFgs2OQfIZeejqXqM4XnH2urUXHDNY5TF66C8nHWgn65x1gg5QMBgqcGdeBQwgKKYYO+yEZatJJ+1MqVFeZX1MsOrIYrrEpT17AiR0G2DkCtPr5/cHvdO9bRI8r1LC8pYU23WJc13aqEchlOCOl3taIGr72duFdgC4fhLiLJ3f7Afrd/+agF4uVX7e0ydIhG0dETPiWD2ur8+O74DdKcTrw6jnC3+tCMHKQ==";

        /// <summary>RSA public key exponent (standard base64; typically <c>AQAB</c>) from key-gen.</summary>
        public const string PublicKeyExponentBase64 = "AQAB";

        /// <summary>
        /// Environment variable a CI/headless build reads the pre-activated entitlement token from,
        /// since it cannot run the interactive Google sign-in. Mirrors how signing passwords are
        /// sourced from the environment in the build pipeline.
        /// </summary>
        public const string EntitlementEnvVar = "MOLCA_LICENSE_ENTITLEMENT";

        /// <summary>Treat an entitlement as expiring this far ahead so builds fail before the token dies.</summary>
        public static readonly TimeSpan ExpirySkew = TimeSpan.FromMinutes(5);

        /// <summary>The <c>/activate-dev</c> endpoint URL.</summary>
        public static string ActivateUrl => $"{ServerBaseUrl.TrimEnd('/')}/activate-dev";

        /// <summary>True once every placeholder has been replaced with real distribution values.</summary>
        public static bool IsConfigured =>
            !ServerBaseUrl.Contains("REPLACE-ME")
            && !GoogleClientId.Contains("REPLACE-ME")
            && !PublicKeyModulusBase64.Contains("REPLACE-ME")
            && !PublicKeyExponentBase64.Contains("REPLACE-ME");
    }
}
