using System;
using System.Collections.Generic;

namespace Molca.ContentPackage.Core
{
    /// <summary>
    /// Top-level version index hosted at the root <c>packages.json</c> URL (schemaVersion 2).
    /// Lists every content version available on the CDN so the app can present version
    /// selection and filter by app compatibility before offering a download.
    /// </summary>
    [Serializable]
    public class ContentVersionIndex
    {
        /// <summary>Always <c>"2"</c> for this type.</summary>
        public string schemaVersion = "2";

        /// <summary>ISO 8601 timestamp written by the build pipeline.</summary>
        public string generatedAt;

        /// <summary>Version string of the most recently published content version.</summary>
        public string latestVersion;

        /// <summary>All versions available on the CDN, newest first by convention.</summary>
        public List<ContentVersionEntry> versions = new List<ContentVersionEntry>();
    }

    /// <summary>
    /// Metadata for a single hosted content version inside <see cref="ContentVersionIndex"/>.
    /// </summary>
    [Serializable]
    public class ContentVersionEntry
    {
        /// <summary>Semantic version string, e.g. <c>"1.1.0"</c>.</summary>
        public string version;

        /// <summary>ISO 8601 publish timestamp.</summary>
        public string releasedAt;

        /// <summary>
        /// Minimum app version required to use this content version.
        /// Empty string means no lower bound.
        /// </summary>
        public string minAppVersion;

        /// <summary>
        /// Maximum app version this content version supports.
        /// Empty string means no upper bound.
        /// </summary>
        public string maxAppVersion;

        /// <summary>Full URL to the Addressables catalog file (<c>catalog_*.bin</c>) for this version.</summary>
        public string catalogUrl;

        /// <summary>Full URL to the per-version <see cref="RemotePackageManifest"/> JSON file.</summary>
        public string manifestUrl;

        /// <summary>Human-readable summary of changes in this version.</summary>
        public string changelog;

        /// <summary>
        /// When <c>true</c> this version is hidden from the UI but remains downloadable
        /// so already-pinned clients are not broken.
        /// </summary>
        public bool isDeprecated;
    }

    /// <summary>
    /// Per-version package manifest fetched from CDN at runtime (schemaVersion 1, or the
    /// version-specific manifest pointed to by <see cref="ContentVersionEntry.manifestUrl"/>).
    /// Generated by the build pipeline and deployed alongside the Addressables catalog.
    /// Contains per-package metadata that can be updated on the CDN without shipping
    /// a new app binary.
    /// </summary>
    [Serializable]
    public class RemotePackageManifest
    {
        /// <summary>Manifest format version for future compatibility.</summary>
        public string schemaVersion = "1";

        /// <summary>ISO 8601 timestamp set by the build pipeline when the manifest was written.</summary>
        public string generatedAt;

        /// <summary>
        /// Full URL of the Addressables catalog file (<c>catalog_*.bin</c>) for this build.
        /// Written by the build pipeline so the runtime can load the correct catalog without
        /// a hardcoded URL baked into the app binary. When present, takes priority over the
        /// catalog URL stored in <see cref="ContentPackageSettings"/>.
        /// </summary>
        public string catalogUrl;

        /// <summary>All package entries in this manifest.</summary>
        public List<RemotePackageEntry> packages = new List<RemotePackageEntry>();

        /// <summary>
        /// Finds the valid entry for <paramref name="packageId"/>, or <c>null</c> if absent.
        /// Skips null and malformed entries so a partially-corrupt CDN manifest cannot throw
        /// or surface unusable metadata.
        /// </summary>
        public RemotePackageEntry FindPackage(string packageId)
            => packages?.Find(p => p != null && p.IsValid() && p.packageId == packageId);
    }

    /// <summary>
    /// Remote metadata for a single content package.
    /// Version and bundle size are written by the build pipeline from actual build output,
    /// making them accurate without requiring an app binary update.
    /// </summary>
    [Serializable]
    public class RemotePackageEntry
    {
        /// <summary>Must match <see cref="ContentPackageSettings.PackageConfig.packageId"/>.</summary>
        public string packageId;

        /// <summary>
        /// Semantic version string updated by the build pipeline on every CDN push.
        /// Used as the primary update-detection signal at runtime.
        /// </summary>
        public string version;

        /// <summary>Human-readable description shown in the package manager UI.</summary>
        public string description;

        /// <summary>Author or team name.</summary>
        public string author;

        /// <summary>Searchable tags for the package manager UI.</summary>
        public string[] tags;

        /// <summary>
        /// Accurate compressed bundle size in bytes, calculated from build output files.
        /// Used as the fallback size when <see cref="UnityEngine.AddressableAssets.Addressables.GetDownloadSizeAsync"/> fails.
        /// </summary>
        public long bundleSizeBytes;

        /// <summary>Optional changelog entry for the latest version.</summary>
        public string changelog;

        /// <summary>
        /// True when this entry carries the minimum data required to be usable — a non-empty
        /// <see cref="packageId"/>. Guards against malformed CDN responses where an entry is
        /// present but missing its identifier.
        /// </summary>
        public bool IsValid() => !string.IsNullOrEmpty(packageId);
    }
}
