using System;

namespace Molca.ReferenceSystem
{
    /// <summary>
    /// Contract for live scene objects that can be registered with and resolved
    /// from the <see cref="ReferenceManager"/> by a string id.
    /// </summary>
    /// <remarks>
    /// Ids are auto-generated by the implementing component (typically via
    /// <see cref="ReferenceGenerator.GenerateUniqueId"/> in <c>OnValidate</c>/<c>Awake</c>);
    /// the <see cref="ReferenceManagerSettings"/> id collections are an editor-time
    /// validation database, not the runtime registry. Only loaded scene
    /// MonoBehaviours (e.g. <c>ReferenceableComponent</c>, <c>Step</c>,
    /// <c>SequenceController</c>) live in the runtime registry — ScriptableObjects
    /// are not runtime-resolvable through this system.
    ///
    /// Example implementation:
    /// <code>
    /// public class MyComponent : MonoBehaviour, IReferenceable
    /// {
    ///     [SerializeField, ReadOnly] private string refId;
    ///
    ///     public string RefId { get => refId; set => refId = value; }
    ///     public string RefType => "MyComponent";
    ///     public string DisplayName => gameObject.name;
    ///
    ///     void Awake()
    ///     {
    ///         if (string.IsNullOrEmpty(refId))
    ///             refId = ReferenceGenerator.GenerateUniqueId(RefType);
    ///         ReferenceManager.Instance.Register(this);
    ///     }
    /// }
    /// </code>
    /// </remarks>
    public interface IReferenceable
    {
        /// <summary>
        /// The unique identifier for this referenceable object, unique within its
        /// <see cref="RefType"/> category. Settable so id-generation and validation
        /// tooling can assign a fresh id.
        /// </summary>
        string RefId { get; set; }

        /// <summary>
        /// The type identifier for this referenceable object.
        /// Used for categorization and type-specific lookups.
        /// </summary>
        string RefType { get; }

        /// <summary>
        /// Optional display name for this referenceable object.
        /// Used for debugging and UI purposes.
        /// </summary>
        string DisplayName { get; }
    }

    /// <summary>
    /// Generic version of IReferenceable with compile-time type safety.
    /// </summary>
    /// <typeparam name="T">The concrete type that implements this interface.</typeparam>
    public interface IReferenceable<T> : IReferenceable where T : IReferenceable<T>
    {
        /// <summary>
        /// Type-safe reference to self. This property helps with fluent APIs and type safety.
        /// </summary>
        T Self => (T)this;
    }
}
